/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e6eeff",
        "surface-container-high": "#dde9ff",
        "surface-container-highest": "#d5e3fd",
        surface: "#f8f9ff",
        "surface-dim": "#ccdbf4",
        "surface-bright": "#f8f9ff",
        "surface-variant": "#d5e3fd",
        "surface-tint": "#49607c",
        "on-surface": "#0d1c2f",
        "on-surface-variant": "#43474d",
        "inverse-surface": "#233144",
        "inverse-on-surface": "#ebf1ff",
        background: "#f8f9ff",
        "on-background": "#0d1c2f",
        outline: "#74777e",
        "outline-variant": "#c3c6ce",

        primary: "#001428",
        "on-primary": "#ffffff",
        "primary-container": "#0f2942",
        "on-primary-container": "#7991af",
        "inverse-primary": "#b0c9e8",
        "primary-fixed": "#d1e4ff",
        "primary-fixed-dim": "#b0c9e8",
        "on-primary-fixed": "#011d35",
        "on-primary-fixed-variant": "#314863",

        secondary: "#226b47",
        "on-secondary": "#ffffff",
        "secondary-container": "#a9f3c5",
        "on-secondary-container": "#29714d",
        "secondary-fixed": "#a9f3c5",
        "secondary-fixed-dim": "#8ed6aa",
        "on-secondary-fixed": "#002111",
        "on-secondary-fixed-variant": "#005232",

        tertiary: "#00132c",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#07284c",
        "on-tertiary-container": "#7690ba",
        "tertiary-fixed": "#d5e3ff",
        "tertiary-fixed-dim": "#adc8f5",
        "on-tertiary-fixed": "#001c3b",
        "on-tertiary-fixed-variant": "#2d486d",

        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        md: "0.375rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-3xs": "0.125rem",
        "space-2xs": "0.125rem",
        "space-xxs": "0.125rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-base": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "space-3xl": "4rem",
        "gutter-mobile": "1rem",
        "gutter-tablet": "1.5rem",
        "gutter-desktop": "1.5rem",
        "gutter-canvas": "1.5rem",
        "margin-mobile": "1rem",
        "margin-tablet": "2rem",
        "margin-desktop": "3rem",
        "container-max": "88rem",
        "max-content-width": "88rem",
        "max-width-content": "80rem",
        "drawer-width": "26rem",
        "panel-rail": "4.5rem",
        "inspector-dock-width": "26rem",
        "workbench-rail-width": "4rem",
        "sidebar-panel-width": "22.5rem",
      },
      fontFamily: {
        "body-sm": ["var(--font-inter)", "sans-serif"],
        "title-md": ["var(--font-inter)", "sans-serif"],
        "label-sm": ["var(--font-inter)", "sans-serif"],
        "headline-md": ["var(--font-inter)", "sans-serif"],
        "headline-xl-mobile": ["var(--font-inter)", "sans-serif"],
        "label-md": ["var(--font-inter)", "sans-serif"],
        "body-md": ["var(--font-inter)", "sans-serif"],
        "headline-lg": ["var(--font-inter)", "sans-serif"],
        "headline-xl": ["var(--font-inter)", "sans-serif"],
        "title-lg": ["var(--font-inter)", "sans-serif"],
        "display-lg": ["var(--font-inter)", "sans-serif"],
        "code-sm": ["var(--font-mono)", "monospace"],
        "body-lg": ["var(--font-inter)", "sans-serif"],
        "headline-sm": ["var(--font-inter)", "sans-serif"],
        caption: ["var(--font-inter)", "sans-serif"],
        "caption-caps": ["var(--font-inter)", "sans-serif"],
        "mono-metric": ["var(--font-mono)", "monospace"],
        "mono-coord": ["var(--font-mono)", "monospace"],
        "mono-tag": ["var(--font-mono)", "monospace"],
        "label-tabular": ["var(--font-mono)", "monospace"],
        "label-code": ["var(--font-mono)", "monospace"],
        serif: ["var(--font-merriweather)", "serif"],
      },
      fontSize: {
        "body-sm": ["0.8125rem", { lineHeight: "1.45", letterSpacing: "0.005em", fontWeight: "400" }],
        "title-md": ["1.125rem", { lineHeight: "1.4", letterSpacing: "0em", fontWeight: "500" }],
        "label-sm": ["0.75rem", { lineHeight: "1.2", letterSpacing: "0.03em", fontWeight: "600" }],
        "headline-md": ["1.5rem", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-xl-mobile": ["1.75rem", { lineHeight: "1.25", letterSpacing: "-0.015em", fontWeight: "700" }],
        "label-md": ["0.875rem", { lineHeight: "1.25", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-md": ["0.9375rem", { lineHeight: "1.5", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg": ["1.875rem", { lineHeight: "1.25", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-xl": ["2.25rem", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "title-lg": ["1.25rem", { lineHeight: "1.4", letterSpacing: "-0.005em", fontWeight: "600" }],
        "display-lg": ["3.5rem", { lineHeight: "1.15", letterSpacing: "-0.025em", fontWeight: "700" }],
        "code-sm": ["0.8125rem", { lineHeight: "1.4", letterSpacing: "0em", fontWeight: "400" }],
        "body-lg": ["1.125rem", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
        "headline-sm": ["1.125rem", { lineHeight: "1.5rem", letterSpacing: "-0.005em", fontWeight: "600" }],
        caption: ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.01em", fontWeight: "500" }],
        "caption-caps": ["0.6875rem", { lineHeight: "0.875rem", letterSpacing: "0.05em", fontWeight: "600" }],
        "mono-metric": ["1.125rem", { lineHeight: "1.5rem", letterSpacing: "-0.02em", fontWeight: "600" }],
        "mono-coord": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.02em", fontWeight: "400" }],
        "mono-tag": ["0.6875rem", { lineHeight: "0.875rem", letterSpacing: "0.04em", fontWeight: "500" }],
        "label-tabular": ["0.75rem", { lineHeight: "1rem", letterSpacing: "-0.01em", fontWeight: "500" }],
        "label-code": ["0.6875rem", { lineHeight: "0.875rem", letterSpacing: "0.02em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
